// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDO0IO4hiL-xGfB5eW3r7SSv6wlVmGdFkc',
    appId: '1:1019630920962:web:093966dbdce4df44f28e1b',
    messagingSenderId: '1019630920962',
    projectId: 'r0ih74w0yudsahfrxih5zsaar2e1nr',
    authDomain: 'r0ih74w0yudsahfrxih5zsaar2e1nr.firebaseapp.com',
    storageBucket: 'r0ih74w0yudsahfrxih5zsaar2e1nr.firebasestorage.app',
    measurementId: 'G-GJ9CNZDKY9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGRjEg-7FdPHD_C-oMsxOU9ZmrcmtHJxk',
    appId: '1:1019630920962:android:e679a748031456f0f28e1b',
    messagingSenderId: '1019630920962',
    projectId: 'r0ih74w0yudsahfrxih5zsaar2e1nr',
    storageBucket: 'r0ih74w0yudsahfrxih5zsaar2e1nr.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCblWxt2aE3vAPZtkP_SWR6t-pZafOq8TI',
    appId: '1:1019630920962:ios:d2fbdb1d4355014bf28e1b',
    messagingSenderId: '1019630920962',
    projectId: 'r0ih74w0yudsahfrxih5zsaar2e1nr',
    storageBucket: 'r0ih74w0yudsahfrxih5zsaar2e1nr.firebasestorage.app',
    iosBundleId: 'com.mergeworks.mergeworks',
  );

}